version: '3'

services:

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    restart: always
    networks:
      - app-network
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      - app


networks:
  app-network:
    driver: bridge 